version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler:2.2.13
      - run: bundle install
      - run: bundle exec rspec
      
  test:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    steps: 
      - checkout
      - run bundle exec rspec 
